#
# Per-user configuration variables
# They are read by a system profile and are passed into home-manager
#

[user]
# Username of the account
username = "solar"
# Description of the account (e.g. full name)
description = "Solar Flare"
# Email address for security configuration
email = "orange.hors@proton.me"
# Selected desktop environment / window manager
desktop = "plasma"  # Either "hyprland" or "plasma"

# Theme settings are used both in system and user Stylix configurations
[theme]
# Color scheme from base16-schemes package
# https://github.com/tinted-theming/base16-schemes
# Previews are avaliable at
# https://tinted-theming.github.io/base16-gallery
colors = "horizon-dark"
# Whether to use a dark or light theme
# Leave empty to select based on the background picture
polarity = "dark"
# Background picture URL
bg_url = "https://derpicdn.net/img/view/2022/3/18/2827797.png"
# Background picture SHA256 (required for bg_url)
bg_sha256 = "f963377fed86229921974be942c8c4c85a8101e3e75664720bfb5a0fdd1a545c"

