#
# Per-system configuration variables
# They are read by a system profile to set up NixOS based on your hardware
#

[hardware]
# UUID of the partition that contains the encrypted LUKS root
# Leave empty if no encryption is used
cryptroot_uuid = "e32cc1df-6798-48bc-93ca-b364e17597b1"
# UUID of a secondary encrypted storage drive to be added to crypttab
# Is unlocked with a key located at `/etc/storage.key`
# Leave empty to not mount the drive
cryptstorage_uuid = "bab5227a-e50d-4143-b246-b19f7989d161"

[system]
# Name of this PC
hostname = "orange-desktop"
# Current timezone (see in `/etc/zoneinfo/` or `/usr/share/zoneinfo/`)
timezone = "Europe/Moscow"
# Default system locale (used for main app and system language)
default_locale = "en_US.UTF-8"
# Additional system locale (used for measurement units and other standards)
additional_locale = "ru_RU.UTF-8"